# Generated by Django 2.0.2 on 2018-02-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='filter_level',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='in_reply_to_status_id',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweeted_status_id',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user_geo_enabled',
        ),
    ]
